### ISSUE TITLE
The shadow of menupopup is not enough soft

### ISSUE THREAD

**Issue by zcyzcy88** [Lootyhoof/maxi4#3]
This is bad:

<img width="225" alt="menu" src="https://user-images.githubusercontent.com/15178410/36062459-106b4bca-0ea8-11e8-824c-2c73cc774e9e.png">
<img width="220" alt="bad" src="https://user-images.githubusercontent.com/15178410/36062465-28543436-0ea8-11e8-856f-f7e936b7ac4b.png">

---

This is good:

<img width="225" alt="good_full" src="https://user-images.githubusercontent.com/15178410/36062500-9d13fb80-0ea8-11e8-96bf-16ada0bd1394.png">
<img width="220" alt="good" src="https://user-images.githubusercontent.com/15178410/36062462-1c87dcca-0ea8-11e8-9a41-541c49f4ca08.png">

**Comment by Lootyhoof** [comment]
This looks to be a DPI scaling thing...if you set `layout.css.devPixelsPerPx` in `about:config` to `1`, does it look normal there (if a bit small)?

**Comment by zcyzcy88** [comment]
Yes, but this is not a feasible solution.

**Comment by Lootyhoof** [comment]
I can't fully support HiDPI resolutions in this theme at this time. This should however help a little with the context menus and tooltips.
