### ISSUE TITLE
Latest release causes vertical lines in autocomplete dropdowns

### ISSUE THREAD

**Issue by pip25** [Lootyhoof/maxi4#4]
See attached screenshot. (It was taken with a Persona enabled, but the result is the same even if I disable it.) This started happening ever since Pale Moon auto-updated the theme a few days ago.
  
![image](https://user-images.githubusercontent.com/11923134/36695045-6a728d82-1b40-11e8-8a80-224e902da584.png)

**Comment by Lootyhoof** [comment]
Thanks for the report! This should now be fixed in v2.0.5.

**Comment by pip25** [comment]
Thanks! I can confirm that the new release indeed fixes the problem on my machine as well.
